### PR TITLE
Fix dropdown & test data-bs usage

### PR DESCRIPTION
**Pull request by machour**
Fixed docs for DropDown and a dismiss in a test

### CODE REVIEW

**Comment by simialbi** [comment]
@machour could you please add the `composer.json` changes to this branch too? That would help run the tests.

**Comment by machour** [comment]
@simialbi all done (I'd advise using a squash & merge instead of a simple merge)

**Comment by simialbi** [comment]
I think here a CHANGELOG entry makes sense. Afterwards I'll merge it.

**Comment by machour** [comment]
@simialbi This is a pure documentation change, I really don't think it should be mentioned in the changelog

**Comment by machour** [comment]
Done :)

**Pull request merged**
