### PR TITLE
Fixed `homeUrl` in default `homeLink`

### PR DESCRIPTION
**Pull request by luke-**
The Phpdoc descriptions says "If this property is not set, it will default to a link pointing to [[\yii\web\Application::homeUrl]] with the label 'Home'. If this property is false, the home link will not be rendered."

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  |

### CODE REVIEW

**Comment by simialbi** [comment]
Please fix test and add a changelog entry

**Comment by luke-** [comment]
@simialbi Hmm, I don't think the failed tests are related to my change.

**Comment by simialbi** [comment]
I think it is:
https://github.com/yiisoft/yii2-bootstrap5/runs/6099493029?check_suite_focus=true

**Comment by luke-** [comment]
@simialbi Oh yes sorry. I was confused by the error message in the PHP 7.0 test. https://github.com/yiisoft/yii2-bootstrap5/runs/6099492941?check_suite_focus=true

**Comment by simialbi** [comment]
Thank you

**Pull request merged**
