### PR TITLE
fix: clientOptions=false skips registerJs

### PR DESCRIPTION
**Pull request by julianrutten**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️ 
| New feature?  | ❌
| Breaks BC?    | ❌ Not compared to previous versions. See issue.
| Fixed issues  | #36

### CODE REVIEW

**Comment by simialbi** [comment]
Hey @julianrutten 
Could you please at a CHANGELOG entry and a Test?

**Comment by WinterSilence** [comment]
@simialbi it's invalid

**Comment by julianrutten** [comment]
@WinterSilence could you elaborate?

**Comment by WinterSilence** [comment]
https://github.com/yiisoft/yii2-bootstrap5/issues/36#issuecomment-1064377588

**Comment by julianrutten** [comment]
Okay so after getting schooled on semantics by @WinterSilence its not up to me to decide if you want this library type safe or not. To be honest yii2 is definitely not type safe. And this is the yii2 library not yii3. Compatibility with previous versions of yii2-bootstrap* should be prioritized. But not my decision as stated. I will use my fork in the meantime.

**Comment by julianrutten** [comment]
Alternative idea: I could add a bool switch for skipping the registerJs on the view. That way the possibility is still there but its correctly typed. Let me know.

**Comment by WinterSilence** [comment]
@julianrutten it's look like https://i-a.d-cd.net/_wAAAgPfLOA-1920.jpg

> Compatibility with previous versions of yii2-bootstrap* should be prioritized.

nope, it's difference packages + BS [major versions are not compatibility](https://semver.org/)

**Comment by julianrutten** [comment]
@WinterSilence It was in the spec before. There is no reason to be rude here. So whats the plan? Can we agree on the fact that there should be a way to render the HTML without registering any javascript (using custom javascript)?

**Comment by WinterSilence** [comment]
@julianrutten it's rude truth

> Can we agree on the fact that there should be a way to render the HTML without registering any javascript (using custom javascript)?

https://github.com/yiisoft/yii2-bootstrap5/issues/36#issuecomment-1064401606

**Comment by julianrutten** [comment]
See #36

**Comment by julianrutten** [comment]
Let me know what you think. I added the tests to the ToastTest, since they all use the same trait.

**Pull request merged**
