### PR TITLE
ActiveField: add rangeInput(), colorInput() and switch mode to checkbox()

### PR DESCRIPTION
**Pull request by WinterSilence**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  |

### CODE REVIEW

**Comment by WinterSilence** [comment]
@simialbi sure, but after maintainers allow changes in PR

**Comment by bizley** [comment]
@WinterSilence simialbi is a mainteiner for this repo, please follow his request.

**Comment by WinterSilence** [comment]
@simialbi done

**Comment by simialbi** [comment]
@WinterSilence Thx for the tests. I miss a switch input test. Could you please add one too?

**Comment by WinterSilence** [comment]
@simialbi done

**Comment by simialbi** [comment]
Thank you

**Pull request merged**
