### PR TITLE
Update BaseHtml

### PR DESCRIPTION
**Pull request by WinterSilence**
Replace PHPDoc of `BaseHtml::$normalizeClassAttribute`
Add inline mode in `BaseHtml::checkboxList()`
Add inline mode in `BaseHtml::radioList()`

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  |

### CODE REVIEW

**Comment by simialbi** [comment]
Could you please update the unit tests and add a CHANGELOG entry?

**Comment by WinterSilence** [comment]
@simialbi done

**Comment by WinterSilence** [comment]
@simialbi I will update tests later

**Comment by simialbi** [comment]
ok, thx

**Comment by WinterSilence** [comment]
@simialbi ups... sorry, I forgot 😅

**Pull request merged**
